version: 0.2

phases:
  build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mvn test
      - ls la
      - mv target/ROOT.war ROOT.war
artifacts:
  files:
    - ROOT.war
    - .ebextensions/**/*
